
# Controls when the workflow will run
on:
  schedule:
    # Runs every 2 minutes
    - cron: '*/2 * * * *'

jobs:
  print-time:
    runs-on: ubuntu-latest

    steps:
    - name: Display time passed
      run: echo "time passed: $(date)"
